replicaCount: 3

image:
  repository: {{.ECR2}}
  tag: "2.7.0"

container:
  name: payments # must also match the name of the container in the argocd application definition

service:
  type: ClusterIP
  port: 8080
  targetPort: 5000
