replicaCount: 3

image:
  repository: {{.ECR1}}
  tag: "1.7.0"

container:
  name: users # must also match the name of the container in the argocd application definition

service:
  type: ClusterIP
  port: 8080
  targetPort: 5000
