apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-argocd-app # name of the app
  namespace: argocd # namespace of the app
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground # this will make argocd delete the resources when the app is deleted

spec:
  project: default # project to deploy to
  source:
    repoURL: ssh://git@github.com/sean-njela/argocd-demo.git
    targetRevision: main # branch to deploy from (or HEAD for latest commit)
    path: environments/dev/apps # path to the apps folder (app of apps pattern)
  destination:
    server: https://kubernetes.default.svc # kubernetes server
    # no namespace specified for root app in app of apps pattern
  syncPolicy:
    syncOptions:
      - CreateNamespace=true # create namespace if it does not exist
      - Validate=true # if the deployment has any issues, it will not be deployed
    automated:
      prune: true # prune resources that are not in the repo
      selfHeal: true # disregard any changes made to the cluster directly
      allowEmpty: false # do not allow empty sync
