---
apiVersion: v1
kind: Secret
metadata:
  name: argocd-image-updater-secret
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  url: ssh://git@github.com/sean-njela/argocd-demo.git
  type: git
  sshPrivateKey: |
      <argocd-image-updater-secret>
  insecure: "false"
  enableLfs: "false"