---
apiVersion: v1
kind: Secret
metadata:
  name: argocd-image-updater-secret
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: ssh://git@github.com/sean-njela/argocd-demo.git
  type: git
  ssh-private-key: LS0tLS1CRUdJTiBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0KYjNCbGJuTnphQzFyWlhrdGRqRUFBQUFBQkc1dmJtVUFBQUFFYm05dVpRQUFBQUFBQUFBQkFBQUFNd0FBQUF0emMyZ3RaVwpReU5UVXhPUUFBQUNEV3BWcWRLM3NoMlNlT1ZWUXBkWWpQb2JBTFNoOTNVQmJXMGZTVkVIaW8vd0FBQUpoWGJoN3pWMjRlCjh3QUFBQXR6YzJndFpXUXlOVFV4T1FBQUFDRFdwVnFkSzNzaDJTZU9WVlFwZFlqUG9iQUxTaDkzVUJiVzBmU1ZFSGlvL3cKQUFBRUJiZXFLUFowOGcxVGQ3TTNDWUJGc3RhTnMvaEh1Z1ZsQkZ6VVRPWTU5RXM5YWxXcDByZXlIWko0NVZWQ2wxaU0raApzQXRLSDNkUUZ0YlI5SlVRZUtqL0FBQUFGR0Z5WjI5alpFQnBiV0ZuWlMxMWNHUmhkR1Z5QVE9PQotLS0tLUVORCBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0K
  insecure: "false"
  enableLfs: "false"
  
#fix