---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: argocd-notifications-secret
  namespace: argocd
spec:
  encryptedData:
    slack-token: AgBiY88TJm1XyBz69Ki4vvK5jWLmqnB3+xXj3hOB6Rl5KAmC0EtG2xDAkf0LRZi4BCVZe4U5Iw2AF5cMzAxugq02n3IEscAYqGBkEMBZeCyV1KwyRlkb/FLs98h+to/z7tYtQgjeG44eV3QGmV5yOHP/komA5y4rdg0f6Bn01dzkCsXaMbPZfhpqcMBURuEIWJoUhSzpjcVitluxkrqVbJNmLV1z2dtanGgaWjHpUsLFRp8JSw7yMG4jYY92QCIpOwtV3y2ac2rd1WkiV+/Dxw3ldNE1bI5lmKcyW3aZ/SezMJPdM+kbOl3a/38ETdSaHhMXmedpJLfA1zff2ozpZnhgLaw6pGX8EhjNdmlE3AO2yRZbnlYt9lLi4WmXxDUfvcAr193wyMA8xaQSs/JBuzzMlbxWIqWBABX1h9vR0EMWqtT2jqdmo5QC5V05jo6kGSiwWLceACIPn1GVDNoiOjogMfwpyIkPVMUEWZDtzrkkF8nNozNPIB0EW6tp5RdeJk3dI2D749BXK3I8ftAqUeMw7kvVFp0AQBkwksARSh3bYvEecOP2nb6ppwFhsFKIG/C2gciVIRHNrnh1Z7BRomLZRdiB3H1JfPL3Yi0H3UAfrVBum+W6gV6qFCmc5ie8nF2uLKChJGxi/gGHMMqngn8530YR0kqdsj6NeleHp51sDHGYwaEUBcCMn+vyALy6DfaCtcTmW2roJyZOruA4MGhSm+BFcWuAMSVhg5eiHwhIvQQHosE7wPaOaL3Swfgkev/UWKFPcH1tYA8=
  template:
    metadata:
      creationTimestamp: null
      name: argocd-notifications-secret
      namespace: argocd
