apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-argocd-app #name of the app
  namespace: argocd #namespace of the app

spec:
  project: demo #project to deploy to
  source:
    repoURL: https://github.com/sean-njela/argocd-demo.git
    targetRevision: main #branch to deploy from (or HEAD for latest commit)
    path: k8s #path to the k8s folder
  destination:
    server: https://kubernetes.default.svc #kubernetes server
    namespace: argocd-demo-ns #namespace to deploy to | argocd-demo-ns is created by argocd if it does not exist
  syncPolicy:
    syncOptions:
      - CreateNamespace=true #create namespace if it does not exist
    automated:
      prune: true #prune resources that are not in the repo
      selfHeal: true #disregeard any changes made to the cluster directly