version: '3'
tasks:
  default:
    desc: "Default command"
    cmds:
      - task --list-all

  ports:
    desc: "This is a command list ports in use"
    cmds:
      - ss -tunl

  create-cluster:
    desc: "Create a Kind cluster if it doesn't already exist"
    cmds:
      - kind create cluster -n argocd-demo --image kindest/node:v1.33.1
    status:
      - kind get clusters | grep -q argocd-demo

  expose-kubeconfig:
    desc: "Expose cluster kubeconfig"
    cmds:
      - cat ~/.kube/config > config-kind-dev.txt
      - echo "Copy config-kind-dev.txt into lens to view your cluster"

  install-argocd:
    desc: "Install or update Argo CD using Terraform"
    dir: terraform
    deps:
      - create-cluster
      - clean-argocd
    cmds:
      - terraform init
      - terraform apply -auto-approve

  forward-argocd-ui:
    desc: "Forward the Argo CD server UI to localhost:8080"
    cmds:
      - kubectl port-forward svc/argocd-server -n argocd 8080:443

  clean-argocd:
    desc: "Deletes any existing Argo CD installation from the cluster"
    cmds:
      - kubectl delete -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml --ignore-not-found=true
      - kubectl delete -n argocd -f 0-application.yaml --ignore-not-found=true
      - kubectl delete -n argocd -f 1-application.yaml --ignore-not-found=true
  
  argocd-init-passwd:
    desc: "This is a command to initialize argocd password. Use admin as username"
    cmds:
      - kubens argocd
      - argocd admin initial-password

  bootstrap-app0:
    desc: "Bootstrap argocd application using app0"
    cmds:
      - kubens argocd
      - kubectl apply -f 0-application.yaml

  tf-delete:
    desc: "Deletes the terraform resources"
    dir: terraform
    cmds:
      - terraform destroy -auto-approve