apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: {{ include "myapp.fullname" . }}
  name: {{ include "myapp.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "myapp.fullname" . }}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{ include "myapp.fullname" . }}
    spec:
      containers:
        - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          name: {{ .Values.container.name }}
          resources: {}
status: {}


