apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: {{ include "myapp.fullname" . }}-service
  name: {{ include "myapp.fullname" . }}-service
spec:
  ports:
    - name: {{ .Values.service.port }}-{{ .Values.service.port }}
      port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: {{ .Values.service.port }}
  selector:
    app: {{ include "myapp.fullname" . }}
  type: {{ .Values.service.type }}
status:
  loadBalancer: {}
