apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: my-argocd-app
  name: my-argocd-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-argocd-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: my-argocd-app
    spec:
      containers:
        - image: nanajanashia/argocd-app:1.0
          ports:
            - containerport: 8080
          name: argocd-app
          resources: {}
status: {}


