apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: myArgoApp-service
  name: myArgoApp-service
spec:
  ports:
    - name: 8080-8080
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: myArgoApp
  type: ClusterIP
status:
  loadBalancer: {}
