apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: my-argocd-app-service
  name: my-argocd-app-service
spec:
  ports:
    - name: 8080-8080
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: my-argocd-app
  type: ClusterIP
status:
  loadBalancer: {}
